### PR TITLE
Updating mailsnake to use requests

### PR DESCRIPTION
**Pull request by maraujop**
This version is using the famous HTTP Python for human beings library https://github.com/kennethreitz/requests
- Moving from urllib2 to requests, turns code neater and shorter
- Refactoring some code
- Adding a basic initial test suite for the library
- Fixing some setup.py flaws, don't forget to add `author_email` to setup.py 

Regards,
Miguel

### CODE REVIEW

**Comment by joncotton** [comment]
+1. Nice work @maraujop!

**Comment by maraujop** [comment]
Thanks :)

**Comment by peterp** [comment]
Will it merge?

**Comment by michaelhelmick** [comment]
@peterp It appears that this repository was abandoned, I've taken the liberty of maintaining this repo at [michaelhelmick/python-mailsnake](https://github.com/michaelhelmick/python-mailsnake)

Feel free to follow updates at that location. I have decided, however, in my fork not to accept this pull request. There is no point in having another dependency on such a small wrapper.

**Comment by maraujop** [comment]
> Feel free to follow updates at that location. I have decided, however, in my fork not to accept this pull request. There is no point in having another dependency on such a small wrapper.

The point could be that requests has way many features. You could extend this to do async calls and many others. As I stated once, I'm not using this wrapper at the moment in current projects.

Cheers,
Miguel

**Comment by michaelhelmick** [comment]
While the async functionality would be nice, I don't think the dependency is needed for functionality you can do with Queue and threading.

I'm not trying to bag on using requests, I think it's a great library and I appreciate your work on this repo.

**Comment by maraujop** [comment]
I understand Mike, no worries at all. It works with urllib2 and that's enough in this case. If the wrapper was more complex, it would be different.

**Pull request closed without merging**
