### PR TITLE
added support for the STS mailchimp service <EOM>

### PR DESCRIPTION
**Pull request by hassek**

### CODE REVIEW

**Comment by michaelhelmick** [comment]
Can you confirm that this works?

I'm planning on making a new MailSnake repo and managing that. I've try to contact @leftium on Facebook and Twitter but to no response. It seems he is no longer supporting this library as his last update was 7 months ago with 4 pull requests outstanding.

So, I'm planning on taking the base library and merging in pull requests for the first commit of myself managing it.

**Comment by hassek** [comment]
yes it works perfectly, I have been using it for at least 4 months without any error. Sounds like a great initiative!

**Comment by michaelhelmick** [comment]
Awesome. I'm seeing exactly how to go about it. What to name it, how to credit it, etc. Unfortunately, I don't think I'll be pulling in @maraujop request (https://github.com/leftium/mailsnake/pull/8) ONLY because why add another dependency. Everything in this wrapper can be accomplished with urllib.

**Comment by michaelhelmick** [comment]
@hassek I'm maintaining this repo here https://github.com/michaelhelmick/python-mailsnake -- Expect to see your pull request pulled in sometime soon!

**Comment by hassek** [comment]
awesome!

**Comment by michaelhelmick** [comment]
@hassek Hey man, any chance you could go to my profile @michaelhelmick and Message me? I wanted to talk about something real fast through email.

**Comment by hassek** [comment]
you need to provide a email address so I can message you

**Comment by michaelhelmick** [comment]
Done. mikeh@ydekproductions.com

**Pull request closed without merging**
